account/urls.py
from django.urls import path

from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.login_account, name='login'),
    path('forget-password/', views.forget_password, name='forget_password'),
    path('register/', views.register_account, name='register'),
    path('logout/', views.Logout, name='logout'),

    path(
        "activate/<slug:uidb64>/<slug:token>/",
        views.activate_email, name="activate"),
    path(
        'resend_activation_link/',
        views.resend_activation_link, name='resend_activation_link'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('export/', views.export, name='export'),
]

freebitcoin/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('panel/', include('panel.urls')),
    path('account/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from . import views


app_name = 'landing'
urlpatterns = [
    path("", views.Index.as_view(), name="landing"),
    path("faq/", views.Faq.as_view(), name="faq"),
    path("gdpr/", views.GDPR.as_view(), name="gdpr"),
    path("blog/", views.Blog.as_view(), name="blog"),
    path(
        "blog/post/<str:slug>/",
        views.BlogDetailPage.as_view(), name="blog-post"),

    # Callable for receiving bitlab request
    path("bitlab/", views.bitlab_callback, name="bitlab-callback"),

    # Callable for receiving cpx request
    path("cpx/", views.cpx_callback, name="cpx-callback"),
]

panel/urls.py
from django.urls import path

from . import views


app_name = 'panel'
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("use-promo-code/", views.view_use_promo_code, name="use_promo_code"),
    path("withdrawals/", views.Withdraw.as_view(), name="withdrawal"),
    path("statistics/", views.Stats.as_view(), name="stats"),
    path("referral/", views.Referral.as_view(), name="referral"),
    path("free-rolls/", views.FreeRollsView.as_view(), name="free_rolls"),
    path(
        "free-rolls/use-link/<int:link_id>/",
        views.use_free_roll_link, name="use_free_rolls"),

    path("messages/", views.Messages.as_view(), name="messages"),
    path(
        "message/detail/<str:slug>/",
        views.MessageDetail.as_view(), name="message-detail"),
    path("earn-more/", views.EarnMorePage.as_view(), name="earn_more"),
    path("redeem/", views.redeem_tokens, name="redeem"),
]

landing/models.py
from django.db import models

# Create your models here.

landing/views.py
from account.models import User
from django.conf import settings
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView, ListView, TemplateView
from panel.models import Post, Transaction, SurveyToken
from .utils import sha1_hash, compare_digest, md5_hash


class Index(TemplateView):
    template_name = 'landing/index.html'
    extra_context = {
        'title': ' | Free OMI Digital Currency | Freeomi.com',
        'homepage': True,
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['site_key'] = settings.HCAPTCHA_SITEKEY

        # Calculate stats
        earning_set = Transaction.objects.get_earned()
        context['stat_users'] = User.objects.count()
        context['stat_games'] = earning_set.count()
        context['stat_earns'] = round(earning_set.sum_amount(), 4)

        return context

    def get(self, request, *args, **kwargs):
        ref = request.GET.get('ref')
        if ref:
            request.session['ref'] = ref
            return redirect('landing:landing')

        if request.user.is_authenticated:
            return redirect('panel:index')

        return super().get(request, *args, **kwargs)


class GDPR(TemplateView):
    template_name = 'landing/gdpr.html'
    extra_context = {
        'title': ' | GDPR'
    }


class Faq(TemplateView):
    template_name = 'landing/faq.html'
    extra_context = {
        'title': ' | Frequently Asked Question'
    }


class Blog(ListView):
    template_name = 'landing/blog.html'
    extra_context = {
        'title': ' | Blog'
    }
    model = Post
    context_object_name = 'posts'
    ordering = '-updated'


class BlogDetailPage(DetailView):
    template_name = 'landing/blog-detail.html'
    model = Post
    context_object_name = 'post'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = ' | Blog | ' + self.get_object().title
        return context


# Survey callbacks
@csrf_exempt
def bitlab_callback(request):
    """
    Callback for receiving bitlab request

    Sample request:
    https://freeomi.com/bitlab/?uid=8cc877ee-af19-488d-b28d-216fb866b996
    &val=4.52&tx=104782
    &hash=dbcd6bb8ca677344592842a52b4fca9bec36cd4b
    """

    url = request.path_info
    uid = request.GET.get('uid')
    val = request.GET.get('val')
    tx = request.GET.get('tx')
    hash = request.GET.get('hash')
    if not uid or not val or not hash:
        return HttpResponseBadRequest('Invalid request')

    # Check hash
    msg = f"https://freeomi.com{url}?uid={uid}&val={val}&tx={tx}"
    if not compare_digest(hash, sha1_hash(msg, settings.BITLAB)):
        return HttpResponseBadRequest('Invalid request')

    try:
        SurveyToken.objects.add_survey_transaction(uid, val, tx)
    except Exception:
        return HttpResponseBadRequest('Invalid request')

    return HttpResponse('OK')


@csrf_exempt
def cpx_callback(request):
    """
    Callback for receiving cpx request

    Sample request:
    https://www.freeomi.com/cpx/?status={status}
    &trans_id={trans_id}&user_id={user_id}
    &amount_local={amount_local}&hash={secure_hash}
    """

    user_id = request.GET.get('user_id')
    trans_id = request.GET.get('trans_id')
    status = request.GET.get('status')
    amount_local = request.GET.get('amount_local')
    hash = request.GET.get('hash')

    # Check hash
    msg = f"{user_id}-{settings.CPX_HASH}"
    if not compare_digest(hash, md5_hash(msg)):
        return HttpResponseBadRequest('Invalid request')

    try:
        if status == '1':
            SurveyToken.objects.add_survey_transaction(
                user_id, amount_local, trans_id)
        else:
            # Delete failed transaction
            tx = SurveyToken.objects.get(txid=trans_id)
            tx.delete()

    except Exception:
        return HttpResponseBadRequest('Invalid request')

    return HttpResponse('OK')

landing/templates/landing/base.html
{% load static %}

{% load mytags %}
{% load google_translate %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang="en"> <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Free Ecomi Cryptocurrency faucet{{ title }}</title>
        <meta name="description" content="Win free Ecomi cryptocurrency after playing a simple game. Get Free Ecomi Digital currency up to $300. We are a free Ecomi faucet &amp; OMI.">
        <meta name="keywords" content="Coin,Faucet,Free,Ecomi,freeomi.com" />
        <meta name="robots" content="index, follow">
        <link rel="canonical" href="website_link_here" />

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}" />
        
        
        <!-- Google fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <link rel="stylesheet" href="{% static 'css/icofont.css' %}">
        <link rel="stylesheet" href="{% static 'css/feather-icon.css' %}">


        <link rel="stylesheet" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" href="{% static 'css/dev.css' %}">

        <script async src="//www.ezojs.com/ezoic/sa.min.js"></script>

    </head>
    <body>

        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        <div id='loader_container'>

            <div id='loader_span'></div>
    
        </div>

        
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
        

        {% if not request.user.is_authenticated %}

            <header class="header nav-header">
                <div class="container">
                    <div class="main-navbar">
                        <nav class="navbar navbar-expand-lg navbar-light">

                            <a id="light_logo_img" class="navbar-brand" href="/"><img src="{% static 'img/logo.png' %}" class="" alt="Free Ecomi"></a>

                            <a id="dark_logo_img" class="navbar-brand" href="/"><img src="{% static 'img/dark_logo.png' %}" class="" alt="Free Bitcoin"></a>


                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'landing:faq' %}">FAQ</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/" data-scroll="mid">Features</a></li>
                                    <li class="nav-item"><a class="nav-link" href="/" data-scroll="bot">Ecomi</a></li>
                                    <li class="nav-item"><a class="nav-link register-link" href="/" data-scroll="top">Register</a></li>
                                    <li class="nav-item"><a class="nav-link login-link" href="/" data-scroll="top">Login</a></li>
                                    <li class="nav-item"><a class="nav-link" target="_blank" href="https://korekuta88.com">OMI MERCH</a></li>

                                    <li class="navbar-twitter"><a href="https://twitter.com/OmiFaucet"></a></li>

                                    <li class="navbar-coins bg-1 visible-lg"><a href="#">1 OMI = ${% get_omi_price %}</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>

                    <div class="clearfix"></div>
                </div>
            </header>

        {% else %}

            <header class="header nav-header {% if not homepage %}loggedin{% endif %}">
                <div class="container-fluid">
                    <div class="main-navbar">
                        <nav class="navbar navbar-expand-lg navbar-light">

                            {% if not homepage %}
                                <a class="navbar-brand" href="/"><img src="{% static 'img/dark_logo.png' %}" class="" alt="Free Bitcoin"></a>
                            {% else %}
                                <a class="navbar-brand" href="/"><img src="{% static 'img/logo.png' %}" class="" alt="Free Bitcoin"></a>
                            {% endif %}

                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
            
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item"><a class="nav-link" href="{% url 'panel:index' %}">Free OMI</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'panel:earn_more' %}" style="font-weight:bold;text-decoration:underline;">Earn More</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'panel:referral' %}">Referral Program</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'landing:faq' %}">FAQ</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'account:settings' %}">Settings</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'panel:stats' %}">Stats</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'panel:withdrawal' %}">Withdrawals</a></li>
                                    <li class="nav-item"><a class="nav-link" href="{% url 'panel:free_rolls' %}" style="font-weight: bold;text-decoration: underline">Free Rolls</a></li>
                                    <li class="nav-item"><a class="nav-link" target="_blank" href="https://korekuta88.com">OMI MERCH</a></li>

                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'panel:messages' %}">
                                            <span class="fa fa-envelope" aria-hidden="true">
                                                <span class="notifications">2</span>
                                            </span>
                                        </a>
                                    </li>

                                    <li class="navbar-twitter"><a target="_blank" href="https://twitter.com/OmiFaucet"></a></li>

                                    <li class="nav-item"><a class="nav-link text-light nav-withdraw bg-2" href="{% url 'panel:withdrawal' %}">Withdraw</a></li>
                                    
                                    <li class="navbar-coins bg-1">
                                        <a href="#">{{ request.user.get_balance }} OMI</a>
                                    </li>
            
                                    <li class="nav-item navbar-logout"><a href="{% url 'account:logout' %}"></a></li>
            
                                </ul>
                            </div>
                        </nav>
                    </div>
            
                    <div class="clearfix"></div>
                </div>
            </header>

            
            {% if not user.verified %}
                <div class="text-white px-2 py-3 text-center" style="background-color: black;">
                    Please confirm your email address by clicking the link we sent to your email account.
                    If you haven't received an email please click <a href="{% url 'account:resend_activation_link' %}">Here</a>.
                    Please remember to check your spam if you can't find the link.
                </div>
            {% endif %}
                

            <a class="withdraw-button bg-2" href="{% url 'panel:withdrawal' %}">Withdraw</a>


        {% endif %}

        <main class="main-wrap">
            {% block content %}
            
            {% endblock content %}
        </main>

<!--        <section id="banner">-->
<!--            <div class="box">-->
<!--                <h2>Win valuable veve prizes</h2>-->
<!--                <p>From as low as $1, you can try your luck and win hundreds of Veve prizes. Visit Vevetale.com today to win NFTs, Comics, OMI, Gems, and shopping discounts, and lot more!</p>-->
<!--                <img src="{% static 'img/x.jpeg' %}" alt="" class="img-fluid mb-4">-->
<!--                <a href="https://vevetale.com/" target="_blank">Try Your Luck From $1 Only</a>-->
<!--            </div>-->
<!--        </section>-->

        <footer>
            <div class="footer-links">
                <p class="copyright">2024, FREEOMI.COM - All rights reserved.</p>
                <p><a href="{% url 'landing:gdpr' %}">GDPR</a> | <a href="{% url 'landing:blog' %}">Blog</a> | <a href='https://www.okx.com/join/9435265'>Free Ecomi Wallet</a></p>
            </div>
        </footer>


        {% block script %}
        
        {% endblock script %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="{% static 'js/feather-icon/feather.min.js' %}"></script>
        <script src="{% static 'js/feather-icon/feather-icon.js' %}"></script>

        <script src="{% static 'js/app.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>

        <script data-host="https://regalanalytics.net" data-dnt="false" src="https://regalanalytics.net/js/script.js" id="ZwSg9rf6GA" async defer></script>
    </body>


</html>

landing/templates/landing/blog-detail.html
{% extends 'landing/base.html' %}
{% load static %}


{% block content %}
<div class="articles-background">
	<div style="background-color: #182961">
		<div class="articles-banner"
						style="background-image: url({% static 'img/freebitcoin/home-main-banner.jpg' %})"></div>
				</div>
	<div class="title-blog-container">
		<h1>Blog</h1>
		<span>FreeOMI.com Blog</span>
	</div>
	<div class="container blog-container articles-container">
		<div class="general">
			<div style="padding:20px 0">
                <div class="text-dark font-weight-bold text-center fs-2">{{ post.title }}</div>
                <p>
					{{ post.content|safe }}
				</p>
				<p style="clear: both;"></p>
			</div>
		</div>
	</div>

</div>
{% endblock content %}

landing/templates/landing/blog.html
{% extends 'landing/base.html' %}
{% load static %}


{% block content %}
    <div class="articles-background">
        <div style="background-color: #182961">
            <div class="articles-banner" style="background-image: url({% static 'img/freebitcoin/home-main-banner.jpg' %})"></div>
        </div>
        <div class="title-blog-container">
            <h1>Blog</h1>
            <span>Freeomi.com Blog</span>
        </div>
        <div class="container blog-container" style="min-height: 750px;">
            <div class="general">
                <div class="row mb-5">
                    <div class="row">
                    </div>
                </div>

                <div class="recent-posts-separator mb-5">RECENT POSTS</div>
                
                <div class="row">
                    
                    {% for post in posts %}
                    <div class="col-lg-4 mb-4">
                        <div class="card">
                            <img class="card-img-top" src="{{ post.get_content_image }}"
                                alt="{{ post.title }}">
                            <div class="card-body">
                                <a class="text-dark text-center" href="{% url 'landing:blog-post' post.slug %}">
                                    <h5 class="card-title">{{ post.title }}</h5>
                                    <p>{{ post.get_content_text|truncatechars:100 }}</p>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                    
                    {% if not posts %}

                    <div class="bg-secondary py-5 px-2 mt-4 rounded d-flex align-items-center justify-content-center">
                        <p class="fs-4 text-light mb-0">No posts yet</p>
                    </div>
                        
                    {% endif %}
                        
                        
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

landing/templates/landing/faq.html
{% extends 'landing/base.html' %}
{% load static %}


{% block content %}

<div class="new-banner faq-bg">
    <div class="overlay"></div>
    
    <div class="banner-content">
        <h2>FAQ</h2>
        <p>(Frequently Asked Questions)</p> 
    </div>
</div>

<div class="general">

    <div class="container">
        <h3 class="color-1">WEBSITE FAQ</h3>

        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">When did Freeomi.com start?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        Freeomi.com has been established and officially launched in August 2022. We worked on the site for a long time prior to launching it.
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">How do I get paid from the site?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        You get paid in Ecomi (OMI). Ecomi is a Crpyto Currency just like Ripple, Ethereum and other Crpyto Currencies. You will get paid to a Ecomi wallet.
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">Where can I get a Ecomi wallet?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        You can get a Ecomi wallet in many places. We do recommend to get a wallet from <a href="https://www.okx.com/join/9435265">https://www.okx.com/</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">Are withdrawals processed instantly?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        Normally, for most members withdrawals will be processed instantly. However, in order to protect our site from fraudulent activity a withdrawal can be held by our security system. If this happens and you genuinely believe this is wrong - then please send us a Direct Message via <a href="https://twitter.com/OmiFaucet">Twitter</a> and we would be happy to assist. 
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">What is the minimum withdrawal amount?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        The minimum is 40,000 OMI
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">Can I have more than 1 account?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        Generally no, and we block such attempts. The only exception is if you forgot your account details and genuinely wishes to start all over again.
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">How do I contact you?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        Please use our Twitter account. You can easily find our Twitter logo in our site.
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">I see a &quot;FAILED&quot; status when I made a withdrawal, what does it mean? And what would happen?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        A &quot;FAILED&quot; status could mainly show up because you either provided invalid withdrawal details (e.g. non-existing wallet, or a ETH wallet instead of a Ecomi wallet). If the transaction fails please update your payment info and our system will try to resend it.
                    </div>
                </div>
            </div>
        </div>
        <div class="faq-line-wrapper bg-1">
            <div class="faq-question">
                <span class="fa fa-plus faq-expension"></span>
                <span class="faq-question-text">Can I get a valid roll with a result great than 10,000 or this is invalid?</span>
            </div>
            <div class="faq-answer">
                <div class="faq-answer-inner">
                    <div class="faq-a-wrapper">
                        <div class="faq-a">A</div>
                    </div>
                    <div>
                        A valid result must be 0-10000 only. Any other result is invalid. We do place a security feature in our site using an invisible Captcha. If you don&#039;t pass that Captcha then you are likely to receive an invalid result. This is done for seucrity purposes. If you are genuinely unable to pass the Captcha then we suggest you Google search &quot;how to pass Captcha&quot; for tips how to do it as you might need to do so with any other site using Captcha services.
                    </div>
                </div>
            </div>
        </div>
        <br><br>
        <!-- Composite Start -->
        {% comment %} <div id="M756877ScriptRootC1216604"></div> {% endcomment %}
        {% comment %} <script src="https://jsc.adskeeper.com/f/r/freeEcomi.io.1216604.js" async></script> {% endcomment %}
        <!-- Composite End -->
    </div>
</div>

{% endblock content %}

landing/templates/landing/gdpr.html
{% extends 'landing/base.html' %}
{% load static %}


{% block content %}

<div class="general">
    <div class="container-fluid p-0">
        <div class="row">
            <div class="banner-wrapper">
                <img src="{% static 'img/freebitcoin/gdpr.jpg' %}" alt="FAQ">
                <div class="header-wrapper">
                    <h1>GDPR</h1>
                    <p class="lead">FreeOMI takes the GDPR extremely seriously and hereby provides full transparency in regards to data collection, data keeping and processing.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container py-5">
        
        <div class="card mb-4 py-4">
            <h5>Data Collection</h5>
            <p>When a publisher signs up to the site, he/she provides an email address and a password. No other information is being provided. The site does not buy user data from any 3rd parties and all the information it collects is collected via registering in the site.</p>
        </div>

        <div class="card mb-4 py-4">
            <h5>How the data is being used</h5>
            <p>The site will never send out unsolicited emails to its users, and will never use the emails our users provide upon registration for any marketing purposes. The only emails the users expect to receive are for password recovery, account confirmation and change of payment details.</p>
        </div>

        <div class="card mb-4 py-4">
            <h5>Is the information stored with freeomi.com secured?</h5>
            <p>We are doing our utmost to ensure the information provided is saved securely and will never share this information with any other party without the user consent. The information the users provide is not accessible to them, and is saved on a secured server with encryption.</p>
        </div>

        <div class="card mb-4 py-4">
            <h5>How the site communicates with its users</h5>
            <p>All communication with the users is being done via the official Twitter account, a clear link to the Twitter account is found in the site itself. All communication such as support inuqiries are dealt with through that page.</p>
        </div>

        <div class="card py-4">
            <h5>Compliance with regulators</h5>
            <p>We are happy to comply with regulators and if needed by all means feel free to keep in touch with us in order to ensure full collaboration between ourselves, our users and regulators accordingly.</p>
        </div>

    </div>
</div>

{% endblock content %}