account/urls.py
from django.urls import path

from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.login_account, name='login'),
    path('forget-password/', views.forget_password, name='forget_password'),
    path('register/', views.register_account, name='register'),
    path('logout/', views.Logout, name='logout'),

    path(
        "activate/<slug:uidb64>/<slug:token>/",
        views.activate_email, name="activate"),
    path(
        'resend_activation_link/',
        views.resend_activation_link, name='resend_activation_link'),
    path('settings/', views.Settings.as_view(), name='settings'),
    path('export/', views.export, name='export'),
]

freebitcoin/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('panel/', include('panel.urls')),
    path('account/', include('account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

panel/urls.py
from django.urls import path

from . import views


app_name = 'panel'
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("use-promo-code/", views.view_use_promo_code, name="use_promo_code"),
    path("withdrawals/", views.Withdraw.as_view(), name="withdrawal"),
    path("statistics/", views.Stats.as_view(), name="stats"),
    path("referral/", views.Referral.as_view(), name="referral"),
    path("free-rolls/", views.FreeRollsView.as_view(), name="free_rolls"),
    path(
        "free-rolls/use-link/<int:link_id>/",
        views.use_free_roll_link, name="use_free_rolls"),

    path("messages/", views.Messages.as_view(), name="messages"),
    path(
        "message/detail/<str:slug>/",
        views.MessageDetail.as_view(), name="message-detail"),
    path("earn-more/", views.EarnMorePage.as_view(), name="earn_more"),
    path("redeem/", views.redeem_tokens, name="redeem"),
]

panel/forms.py
from decimal import Decimal
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from django.conf import settings
from hcaptcha.fields import hCaptchaField

from .models import Post, Message, WithdrawalRequest


class CaptchaForm(forms.Form):
    hcaptcha = hCaptchaField()


class PostAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Post
        fields = ('title', 'slug', 'image', 'content')


class MessageAdminForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = Message
        fields = ('title', 'content')


class WithdrawalForm(forms.ModelForm):

    class Meta:
        model = WithdrawalRequest
        fields = ('amount',)

    @property
    def user(self):
        return self.initial['user']

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        balance = self.user.get_balance()

        if amount < settings.MIN_WITHDRAWAL:
            raise forms.ValidationError(
                f"Minimum withdrawal is {settings.MIN_WITHDRAWAL} OMI")

        if amount > float(balance):
            raise forms.ValidationError(
                f"Insufficient funds. You have {balance} OMI")

        return amount

    def save(self):
        instance = super().save(commit=False)
        instance.user = self.user
        instance.address = self.user.profile.withdraw_address
        instance.save()
        return instance

panel/views.py
from random import randint
from typing import Any, Dict

from account.models import User
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, TemplateView
from utils.general import (get_last_n_days, get_total_seconds_from_start,
                           is_ajax)

from .models import FreeRollLink, Message, PromoCode, RollValue, Transaction
from .forms import WithdrawalForm


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'panel/index.html'
    extra_context = {
        'title': ' | Freeomi.com | Start rolling!'
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['roll_values'] = RollValue.objects\
            .all().order_by('payout_dollar')

        # Calculate remaining time
        now_time = get_total_seconds_from_start()
        last_roll = self.request.user.profile.roll_time
        required_lap_in_seconds = settings.ROLL_SECONDS
        interval = now_time - last_roll
        remaining_time = 0
        if 0 <= interval < required_lap_in_seconds:
            remaining_time = required_lap_in_seconds - interval

        context['remaining_time'] = remaining_time

        return context

    def post(self, request, *args, **kwargs):

        if is_ajax(request):
            now_time = get_total_seconds_from_start()
            last_roll = request.user.profile.roll_time
            required_lap_in_seconds = settings.ROLL_SECONDS
            interval = now_time - last_roll
            if required_lap_in_seconds > interval >= 0:
                data = {
                    'message': 'Not yet time'
                }
                return JsonResponse(data, status=400)

            data = {
                'lucky_number': 0,
                'pending_rolls': 0,
                'remaining_seconds': required_lap_in_seconds,
                'coins_won': 0,
                'total_coins': 0,
            }

            roll = randint(0, 300)
            data['lucky_number'] = roll
            roll_value = RollValue.objects\
                .filter(lucky_number_start__lte=roll)\
                .filter(lucky_number_end__gte=roll).first()
            token_won = roll_value.value_in_omi
            data['coins_won'] = token_won

            request.user.transaction_set.create(
                tx_type='earn',
                credit=True,
                amount=token_won,
            )
            if request.user.transaction_set.count() <= 1:
                data['first'] = True

            data['total_coins'] = request.user.get_balance()

            request.user.profile.roll_time = now_time
            request.user.profile.save()
            return JsonResponse(data, status=200)


@login_required
def view_use_promo_code(request):
    """
    Check if user can use promo code
    and if so, use it
    Returns redirect to the same page if user
    can't use promo code
    """
    if is_ajax(request):
        code = request.POST.get('code')
        promo_code = PromoCode.objects.filter(code=code)\
            .filter(valid_until__gte=timezone.now()).first()
        if promo_code and \
            not request.user.profile.has_used_promo_code(
                promo_code):
            request.user.profile.use_promo_code(promo_code)
            data = {
                'message': 'Promo code applied, roll again!'
            }
            return JsonResponse(data, status=200)

    data = {
        'message': 'Promo code is not valid, expired or already used'
    }
    return JsonResponse(data, status=400)


class Withdraw(LoginRequiredMixin, TemplateView):
    template_name = 'panel/withdrawal.html'
    extra_context = {
        'title': ' | Withdrawals'
    }

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['withdrawals'] = self.request.user.withdrawalrequest_set.all()
        return context

    def post(self, request, *args, **kwargs):
        form = WithdrawalForm(data=request.POST, initial={
            "user": self.request.user
        })

        if form.is_valid():
            form.save()
            messages.success(
                request, "Withdrawal request sent, \
will be completed in a few days. You can check your withdrawal requests in \
`My Withdrawal` tab below.")
            return redirect("panel:withdrawal")

        context = self.get_context_data()
        context['form'] = form
        return self.render_to_response(context)


class Stats(LoginRequiredMixin, TemplateView):
    template_name = 'panel/stats.html'
    extra_context = {
        'title': ' | Statistics'
    }

    def format_last_days(self):
        return [
            day.strftime("%d %b, %Y")
            for day in
            self.last_days
        ]

    def get_ecomi_won_analysis(self):
        values = [
            self.token_queryset.get_earned().date_sum_amount(date)
            for date in
            self.last_days
        ]

        template = [
            {
                "date": date,
                "value": value
            }
            for date, value in
            zip(self.last_days_format, values)
        ]

        analysis = {
            "name": f"Ecomi won in the last {len(self.last_days)} days",
            "dates": self.last_days_format,
            "values": values,
            "template": template
        }
        return analysis

    def get_referral_analysis(self):
        values = [
            self.token_queryset.get_referrals().date_sum_amount(date)
            for date in
            self.last_days
        ]

        template = [
            {
                "date": date,
                "value": value
            }
            for date, value in
            zip(self.last_days_format, values)
        ]

        analysis = {
            "name": f"Referral commission earned in \
last {len(self.last_days)} days",
            "dates": self.last_days_format,
            "values": values,
            "template": template
        }
        return analysis

    def get_payment_analysis(self):
        values = [
            self.token_queryset.get_payments().date_sum_amount(date)
            for date in
            self.last_days
        ]

        template = [
            {
                "date": date,
                "value": value
            }
            for date, value in
            zip(self.last_days_format, values)
        ]

        analysis = {
            "name": f"Payments sent in \
last {len(self.last_days)} days",
            "dates": self.last_days_format,
            "values": values,
            "template": template
        }
        return analysis

    def get_users_analysis(self):
        addition = timezone.timedelta(days=1)
        values = [
            User.objects.filter(
                created__gte=date
            ).filter(
                created__lt=(date + addition)
            ).count()
            for date in
            self.last_days
        ]

        template = [
            {
                "date": date,
                "value": value
            }
            for date, value in
            zip(self.last_days_format, values)
        ]

        analysis = {
            "name": f"User registration in \
last {len(self.last_days)} days",
            "dates": self.last_days_format,
            "values": values,
            "template": template
        }
        return analysis

    def get_token_analysis(self):
        values = [
            self.token_queryset.get_earned().date_sum_amount(date)
            for date in
            self.last_days
        ]

        template = [
            {
                "date": date,
                "value": value
            }
            for date, value in
            zip(self.last_days_format, values)
        ]

        analysis = {
            "name": f"Tokens earned in \
last {len(self.last_days)} days",
            "dates": self.last_days_format,
            "values": values,
            "template": template
        }
        return analysis

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        self.token_queryset = Transaction.objects.all()
        self.last_days = get_last_n_days(10)
        self.last_days_format = self.format_last_days()

        context["analysis"] = {
            "ecomi_won": self.get_ecomi_won_analysis(),
            "referral_commission": self.get_referral_analysis(),
            "payments_sent": self.get_payment_analysis(),
            "users_registered": self.get_users_analysis(),
            "token_won": self.get_token_analysis(),
        }

        return context


class Referral(LoginRequiredMixin, TemplateView):
    template_name = 'panel/referral.html'
    extra_context = {
        'title': ' | Referral Program'
    }

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['site'] = get_current_site(self.request).domain
        context['total_earned'] = self.request.user.total_earned_referral()
        context['recent_earned'] = self.request.user.recent_earned_referral()
        return context


class FreeRollsView(LoginRequiredMixin, TemplateView):
    template_name = 'panel/free-rolls.html'
    extra_context = {
        'title': ' | Get Free Rolls'
    }

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['lifetime'] = round(settings.ROLL_LINK_LIFETIME / 60 / 60)

panel/templates/panel/earn_more.html
{% extends 'landing/base.html' %}
{% load static %}
{% load mytags %}


{% block content %}

<div class="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-lg-10 offset-lg-1">
                
                <h2>Earn More</h2>

                <div class="row align-items-stretch mt-3 mb-5">
                    <div class="col-md-12">
                        <div class="bg-info text-light rounded dbox">
                            You can earn a lot more tokens with our free surveys and offers. Then redeem them to get more OMI tokens.
                        </div>
                    </div>
                    <div class="ms-auto col-md-6 mt-5">
                        <button class="redeem-button main-button-2 bg-2 mb-5 ms-auto me-0" data-bs-toggle="modal" data-bs-target="#redeemModal">Redeem tokens to OMI</button>
                    </div>
                </div>


                <div class="modal fade" id="redeemModal" tabindex="-1" aria-labelledby="redeemModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h3 class="modal-title" id="redeemModalLabel">Redeem your tokens in OMI</h3>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p>Redeem your tokens to your Crypto balance. The value is shown is USD but the balance would be added to your Crypto balance in the site.</p>
                                <p>If you got kicked out of a survey click the menu to contact CPX and they will look into your case. Check several times per day if there are new surveys for you!</p>

                                <p>{{ tokens_per_usd }} tokens = 1$</p>
                                <p>Your Tokens: {{ request.user.token_balance_text }} tokens</p>
                                <p>Your Tokens in OMI: {{ request.user.token_balance_in_omi }} OMI</p>
                                <p>MINIMUM REDEMPTION AMOUNT: {{ min_withdraw }} TOKENS</p>

                                <form action="{% url 'panel:redeem' %}" method="post">

                                    <div class="mb-3">
                                        <label for="amount_id" class="form-label">
                                            <span>Amount</span>
                                            <p data-amount="{{ request.user.token_balance }}">Redeem All</p>
                                        </label>
                                        <input required name="amount" type="number" class="form-control" id="amount_id" placeholder="Enter amount of tokens to redeem">
                                    </div>

                                    <p class="text-danger my-2"></p>

                                    <button type="submit" class="btn btn-primary btn-lg">Redeem</button>

                                </form>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="advertisers-wrapper">
                    <div class="advertisers">
                        <div class="iframe-wrapper">
                            <a class="link" data-tab="bitlab">
                                <img src="{% static 'img/tokens/bitlabs.jpg' %}" width="50px">
                            </a>
                            <a class="link-text">BitLabs</a>
                        </div>
                        <div class="iframe-wrapper">
                            <a class="link" data-tab="cpx">
                                <img src="{% static 'img/tokens/cpxresearch.png' %}" width="50px">
                            </a>
                            <a class="link-text">CPXResearch</a>
                        </div>
                        <div class="iframe-wrapper">
                            <a class="link" data-tab="timewall">
                                <img src="{% static 'img/tokens/timewall.png' %}" width="50px">
                            </a>
                            <a class="link-text">TimeWall</a>
                        </div>
                    </div>
                </div>

                <style>

                    iframe {
                        height: 1000px;
                        width: 100%;
                        padding: 0px;
                    }

                </style>

                <div class="offerwalls-output"></div>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}
    

panel/templates/panel/free-rolls.html
{% extends 'landing/base.html' %}
{% load static %}
{% load mytags %}


{% block content %}

<div class="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-lg-10 offset-lg-1">
                
                <h2>Free Roll links</h2>

                <div class="bg-info text-light rounded p-3 my-3">
                    Links can be used once every 24 hours. Make sure to visit 1 link at a time and after you use the FREE roll, visit another link for another FREE roll! If you open multiple links consecutively without rolling in between, you will end up wasting your free rolls and will only get one!
                </div>

                <div class="row free-link-rolls">
                    {% for link in freebitcoin_links %}
                        <div class="col-xs-12 col-lg-6 my-3">
                            <div class="card {% has_used_link user link %}">
                                <div class="card-body">
                                    <h3 class="card-title">Free Roll Link {{ forloop.counter }}</h3>
                                    <p class="card-text">
                                        <a href="{% url 'panel:use_free_rolls' link.id %}" class="btn btn-info" target="_blank">Visit</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}
    

panel/templates/panel/index.html
{% extends 'landing/base.html' %}
{% load static %}

{% block content %}

<!-- Ezoic - top_of_page - top_of_page -->
<div id="ezoic-pub-ad-placeholder-104">
    <script async="" src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js">
    </script>
    <ins class="adsbygoogle" style="display:inline-block;width:468px;height:60px"
    data-ad-client="ca-pub-123456789101112"
    data-ad-slot="5744848575"></ins>
    <script>(window.adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<!-- End Ezoic - top_of_page - top_of_page -->
<!-- Ezoic - sidebar - sidebar -->
<!--<div id="ezoic-pub-ad-placeholder-103"> </div>-->
<!-- End Ezoic - sidebar - sidebar -->
<div class="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">

                <div class="free">

                    <span id="remaining_time" class="d-none">{{ remaining_time }}</span>
                        <div style="display: flex; justify-content: space-between; width: 100%; z-index: 999;" class="desktop-ad">
                            <div class="iframe-container" style="order: 1;">
                               <iframe src='https://ads.coinserom.com/publisher?adsunit=&serom=3131373433&size=300x250' style='width:300px;height:250px;border:0px;padding:0;background-color: transparent;overflow: auto;'>
                            </iframe>
                            </div>
                            <div class="iframe-container" style="order: 2;">
                                <iframe src='https://ads.coinserom.com/publisher?adsunit=&serom=3131373433&size=300x250' style='width:300px;height:250px;border:0px;padding:0;background-color: transparent;overflow: auto;'>
                            </iframe>
                            </div>
                            <div class="iframe-container" style="order: 2;">
                                <iframe src='https://ads.coinserom.com/publisher?adsunit=&serom=3131373433&size=300x250' style='width:300px;height:250px;border:0px;padding:0;background-color: transparent;overflow: auto;'>
                            </iframe>
                            </div>

                        </div>
                    <div>
                        <div class="mobile-ad" style="display: none;">
                            <iframe src='https://ads.coinserom.com/publisher?adsunit=&serom=3131373433&size=728x90' style='border:0px;padding:0;background-color: transparent;overflow: auto;'></iframe>
                        </div>
                    </div>
                    <h1 class="color-other">THIS GAME IS PROBABLY FAIR!</h1>

                    <p class="top-text">
                        Please click on the ROLL button to get your Free OMI. The amount of Free OMI that you get will depend on the number that you roll and paid out according to the payout table below. You can come back and play every hour to win additional Free OMI each time! You would also get 50% of what your referrals get from us as well.
                        <br><br>
                    </p>

                    <div class="col-xs-12 col-md-4 offset-md-4 col-sm-6 offset-sm-3">
                        <div class="form-group">
                            <label>Please enter your promo code: (check our <a href="https://twitter.com/OmiFaucet" target="_blank">twitter</a>)</label>
                            <div class="input-group">
                                <input data-url="{% url 'panel:use_promo_code' %}" id="promo-code" type="text" name="code" class="form-control" placeholder="Promo code">
                                <span class="input-group-btn">
                                    <button id="submit-promo-code" type="button" class="btn main-button-blue-simple submit-promo" style="color:white">Go!</button>
                                </span>
                            </div>
                            <p class="text-center">
                                <br>
                                - OR -
                                <br>
                                <br>
                                <span style="font-weight:bold">Visit the <a href="{% url 'panel:free_rolls' %}">FREE ROLLS</a> page</span>
                            </p>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-10 offset-md-1 table-wrapper">
                        <div class="timeout-wrapper">
                            <h3 class="color-dark">Countdown to next ROLL!</h3>

                            <div class="timeout-container">
                                <div class="minutes">
                                    <div class="digits">0</div>
                                    <div class="label">MINUTES</div>
                                </div>

                                <div class="seconds">
                                    <div class="digits">0</div>
                                    <div class="label">SECONDS</div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <table>
                                    <tr>
                                        <th class="bg-dark border-1">LUCKY NUMBER</th>
                                        <th class="bg-dark border-1">PAYOUT</th>
                                        <th class="bg-dark border-1">SHOW VALUE IN OMI</th>
                                    </tr>

                                    
                                    {% for v in roll_values %}
                                        <tr>
                                            <td class="bg-dark border-1">{{ v.roll_range }}</td>
                                            <td class="bg-dark border-1">{{ v.payout }}</td>
                                            <td class="bg-dark border-1">{{ v.value_in_omi }}</td>
                                        </tr>
                                    {% endfor %}
                                        
                                </table>
                            </div>

                            <div class="col-md-6">
                                <div id="taboola-right-rail-thumbnails"></div>
                                <script type="text/javascript">
                                </script>
                            </div>
                        </div>

                        <div class="lucky-numbers">
                            <div class="lucky-number-wrapper">
                                <div class="lucky-number digit-1">0</div>
                            </div>
                            <div class="lucky-number-wrapper">
                                <div class="lucky-number digit-2">0</div>
                            </div>  
                            <div class="lucky-number-wrapper">
                                <div class="lucky-number digit-3">0</div>
                            </div>  
                            <div class="lucky-number-wrapper">
                                <div class="lucky-number digit-4">0</div>
                            </div>  
                            <div class="lucky-number-wrapper">
                                <div class="lucky-number digit-5">0</div>
                            </div>
                        </div>

                        <div class="result"></div>
                    </div>

                    <div class="clearfix"></div>
                    
                    <div class="roll-wrapper">
                        <div class="h-captcha"></div>
                        <button class="main-button-2 roll-button bg-2">ROLL!</button>
                        <br>
                        <p class="text-center">
                            <span class="pending-rolls">You can roll 1 more times.</span>
                        </p>
                    </div>

                    <style>
                        #coinzilla img{
                            display: block;
                            margin: 3rem auto;
                        }
                    </style>

                    <a id="coinzilla" href="https://coinzilla.com/ref/37462ed6a653c240815/" target="_blank">
                        <img src="{% static 'img/banner1.jpeg' %}" alt="">
                    </a>


                    <!-- Button trigger modal -->
                    <button id="lauchEarnMore" type="button" class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Launch demo modal
                    </button>


                    <style>

                        #exampleModal h5{
                            font-size: 1.6rem;
                        }

                        #exampleModal p{
                            font-size: 1.2rem;
                            line-height: 2;
                        }

                        #exampleModal .btn{
                            padding: .8rem 2rem;
                            font-size: 1.2rem;
                        }

                    </style>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header py-4">
                                <h5 class="modal-title" id="exampleModalLabel">Earn More with Surveys</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body py-4">
                                <p>Whilst waiting for another roll you can earn so much
                                    more by completing survey! Increase your earnings now.
                                </p>
                            </div>
                            <div class="modal-footer d-flex align-items-center justify-content-center py-3">
                                <a href="{% url 'panel:earn_more' %}" class="btn btn-outline-danger">Go to Earn More Page</a>
                            </div>
                        </div>
                        </div>
                    </div>
  
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!--<script>-->
<!--    window.ezstandalone = window.ezstandalone || {};-->
<!--    ezstandalone.cmd = ezstandalone.cmd || [];-->
<!--    ezstandalone.cmd.push(function() {-->
<!--        ezstandalone.define(103);-->
<!--        ezstandalone.enable();-->
<!--        console.log(ezstandalone);-->
<!--        ezstandalone.display();-->

<!--    });-->
<!--</script>-->

{% endblock content %}